### ISSUE TITLE
Call to __get_system_markets() causes KeyError when Initializing Object

### ISSUE THREAD

**Issue by rayray221** [turbonomic/vmt-connect#4]
When initializing a vmtconnect object against an instance that has a unnamed custom market, the following error is thrown:

```
Traceback (most recent call last):
  File "/opt/turbonomic/vra-reconcile.py", line 472, in <module>
    main()
  File "/opt/turbonomic/vra-reconcile.py", line 65, in main
    vmt = vc.Session(host=config['target'], username=username, password=password)
  File "/usr/local/lib/python3.8/site-packages/vmtconnect/vmtconnect.py", line 1972, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/vmtconnect/vmtconnect.py", line 802, in __init__
    self.__get_system_markets()
  File "/usr/local/lib/python3.8/site-packages/vmtconnect/vmtconnect.py", line 907, in __get_system_markets
    self.__system_market_ids = [x['uuid'] for x in res if x['displayName'] in self.__system_markets]
  File "/usr/local/lib/python3.8/site-packages/vmtconnect/vmtconnect.py", line 907, in <listcomp>
    self.__system_market_ids = [x['uuid'] for x in res if x['displayName'] in self.__system_markets]
KeyError: 'displayName'
```

The following is the DTO response for the /api/v3/markets call:
```
[
    {
        "uuid": "777777",
        "displayName": "Market",
        "className": "Market",
        "state": "RUNNING",
        "stateProgress": 100,
        "unplacedEntities": false,
        "environmentType": "HYBRID"
    },
    {
        "uuid": "214335654448944",
        "className": "Market",
        "state": "SUCCEEDED",
        "stateProgress": 100,
        "scenario": {
            "uuid": "0",
            "displayName": "",
            "owners": [
                {
                    "uuid": "SYSTEM",
                    "showSharedUserSC": false
                }
            ],
            "type": "CUSTOM",
            "scope": [
                {
                    "uuid": "Market",
                    "displayName": "Global Environment",
                    "className": "Market"
                }
            ],
            "projectionDays": [
                0
            ],
            "topologyChanges": {},
            "loadChanges": {
                "utilizationList": [],
                "maxUtilizationList": []
            },
            "configChanges": {
                "addPolicyList": [],
                "removePolicyList": [],
                "automationSettingList": [
                    {
                        "uuid": "move",
                        "displayName": "Move",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "Container"
                    },
                    {
                        "uuid": "move",
                        "displayName": "Move",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "Storage"
                    },
                    {
                        "uuid": "move",
                        "displayName": "Move",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "ContainerPod"
                    },
                    {
                        "uuid": "move",
                        "displayName": "Move",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "DiskArray"
                    },
                    {
                        "uuid": "move",
                        "displayName": "Move",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "VirtualVolume"
                    },
                    {
                        "uuid": "move",
                        "displayName": "Move",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "LogicalPool"
                    },
                    {
                        "uuid": "move",
                        "displayName": "Move",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "VirtualMachine"
                    },
                    {
                        "uuid": "provision",
                        "displayName": "Provision",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "PhysicalMachine"
                    },
                    {
                        "uuid": "provision",
                        "displayName": "Provision",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "Container"
                    },
                    {
                        "uuid": "provision",
                        "displayName": "Provision",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "Storage"
                    },
                    {
                        "uuid": "provision",
                        "displayName": "Provision",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "ApplicationComponent"
                    },
                    {
                        "uuid": "provision",
                        "displayName": "Provision",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "ContainerPod"
                    },
                    {
                        "uuid": "provision",
                        "displayName": "Provision",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "DiskArray"
                    },
                    {
                        "uuid": "provision",
                        "displayName": "Provision",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "StorageController"
                    },
                    {
                        "uuid": "provision",
                        "displayName": "Provision",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "LogicalPool"
                    },
                    {
                        "uuid": "provision",
                        "displayName": "Provision",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "VirtualMachine"
                    },
                    {
                        "uuid": "storageMove",
                        "displayName": "Storage Move",
                        "value": "DISABLED",
                        "defaultValue": "RECOMMEND",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "VirtualMachine"
                    },
                    {
                        "uuid": "resize",
                        "displayName": "Resize",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "Container"
                    },
                    {
                        "uuid": "resize",
                        "displayName": "Resize",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "Storage"
                    },
                    {
                        "uuid": "resize",
                        "displayName": "Resize",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "WorkloadController"
                    },
                    {
                        "uuid": "resize",
                        "displayName": "Resize",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "DiskArray"
                    },
                    {
                        "uuid": "resize",
                        "displayName": "Resize",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "DatabaseServer"
                    },
                    {
                        "uuid": "resize",
                        "displayName": "Resize",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "LogicalPool"
                    },
                    {
                        "uuid": "suspend",
                        "displayName": "Suspend",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "PhysicalMachine"
                    },
                    {
                        "uuid": "suspend",
                        "displayName": "Suspend",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "Container"
                    },
                    {
                        "uuid": "suspend",
                        "displayName": "Suspend",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "Storage"
                    },
                    {
                        "uuid": "suspend",
                        "displayName": "Suspend",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "ApplicationComponent"
                    },
                    {
                        "uuid": "suspend",
                        "displayName": "Suspend",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "ContainerPod"
                    },
                    {
                        "uuid": "suspend",
                        "displayName": "Suspend",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "DiskArray"
                    },
                    {
                        "uuid": "suspend",
                        "displayName": "Suspend",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "LogicalPool"
                    },
                    {
                        "uuid": "suspend",
                        "displayName": "Suspend",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "VirtualMachine"
                    },
                    {
                        "uuid": "reconfigure",
                        "displayName": "Reconfigure",
                        "value": "DISABLED",
                        "defaultValue": "RECOMMEND",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            }
                        ],
                        "entityType": "ContainerPod"
                    },
                    {
                        "uuid": "reconfigure",
                        "displayName": "Reconfigure",
                        "value": "DISABLED",
                        "defaultValue": "RECOMMEND",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            }
                        ],
                        "entityType": "VirtualMachine"
                    },
                    {
                        "uuid": "activate",
                        "displayName": "Start",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "PhysicalMachine"
                    },
                    {
                        "uuid": "activate",
                        "displayName": "Start",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "Container"
                    },
                    {
                        "uuid": "activate",
                        "displayName": "Start",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "Storage"
                    },
                    {
                        "uuid": "activate",
                        "displayName": "Start",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "ContainerPod"
                    },
                    {
                        "uuid": "activate",
                        "displayName": "Start",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "DiskArray"
                    },
                    {
                        "uuid": "activate",
                        "displayName": "Start",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "LogicalPool"
                    },
                    {
                        "uuid": "activate",
                        "displayName": "Start",
                        "value": "DISABLED",
                        "defaultValue": "MANUAL",
                        "valueType": "STRING",
                        "valueObjectType": "String",
                        "options": [
                            {
                                "label": "Disabled",
                                "value": "DISABLED"
                            },
                            {
                                "label": "Recommend",
                                "value": "RECOMMEND"
                            },
                            {
                                "label": "External Approval",
                                "value": "EXTERNAL_APPROVAL"
                            },
                            {
                                "label": "Manual",
                                "value": "MANUAL"
                            },
                            {
                                "label": "Automatic",
                                "value": "AUTOMATIC"
                            }
                        ],
                        "entityType": "VirtualMachine"
                    }
                ],
                "removeConstraintList": [],
                "riSettingList": []
            }
        },
        "saved": true,
        "runDate": "2020-08-19T17:50:54Z",
        "runCompleteDate": "2020-08-19T17:50:55Z"
    }
]
```

As can be seen, the second market which is a customer one is missing a displayName.  vmtconnect should be able to instantiate an object even if other custom markets exist without displayName.

**Comment by rastern** [comment]
Fixed in next release
